DROP DATABASE IF EXISTS letour;
DROP SCHEMA IF EXISTS public;
DROP USER IF EXISTS letour;

CREATE SCHEMA public;
CREATE DATABASE letour;
CREATE USER letour WITH ENCRYPTED PASSWORD 'v1';
GRANT ALL PRIVILEGES ON DATABASE letour TO letour;
GRANT ALL ON SCHEMA public TO letour;
