CREATE SCHEMA IF NOT EXISTS public;
SELECT 'CREATE DATABASE letour' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'letour')\gexec
CREATE USER letour WITH ENCRYPTED PASSWORD :'LETOUR_PASS';
GRANT ALL PRIVILEGES ON DATABASE letour TO letour;
GRANT ALL ON SCHEMA public TO letour;
